function Caa = CaaPoly(C,G,L,P,TB,alpha,beta,gamma)

% This function returns the vector of monomial coefficients for the Caa
% polynomial which corresponds to the reaction function of firm A.

% This polynomial is derived according to the assumption LA = LB = L and 
% PA = PB = P.

% Define the polynomial coefficient vectors Caa.
Caa = [ -G, ...
        - 3*G*L - 3*G*TB, ...
        2*L*alpha^2 - 3*G*TB^2 - 3*G*L^2 + 2*TB*alpha^2 - 6*G*L*TB ...
        - 2*C*L*alpha - 2*C*TB*alpha + 2*C*TB*beta - 2*L*alpha*gamma ...
        - 2*TB*alpha*beta - 2*TB*alpha*gamma + 2*TB*beta*gamma ...
        - 2*L*P*alpha^2 + 2*C*L*P*alpha + 2*C*L*P*beta ...
        - 2*L*P*alpha*beta + 2*L*P*alpha*gamma + 2*L*P*beta*gamma, ...
        2*L^2*P*alpha^2 - G*TB^3 - 2*TB^2*beta^2 - G*L^3 - ...
        2*L^2*P^2*alpha^2 - 2*L^2*P^2*beta^2 - 3*G*L*TB^2 - 3*G*L^2*TB ...
        - 2*C*L^2*alpha - 2*C*TB^2*alpha + 2*C*TB^2*beta ...
        - 2*L^2*alpha*gamma + 2*TB^2*alpha*beta - 2*TB^2*alpha*gamma ...
        + 2*TB^2*beta*gamma + 2*C*L^2*P*beta + 2*L*P*TB*alpha^2 ...
        - 4*L*P*TB*beta^2 + 2*L^2*P*alpha*beta + 2*L^2*P*alpha*gamma ...
        + 2*L^2*P*beta*gamma - 4*L^2*P^2*alpha*beta - 4*C*L*TB*alpha ...
        + 2*C*L*TB*beta + 2*L*TB*alpha*beta - 4*L*TB*alpha*gamma ...
        + 2*L*TB*beta*gamma + 2*C*L^2*P*alpha - 2*L*P*TB*alpha*beta ...
        + 2*L*P*TB*alpha*gamma + 2*L*P*TB*beta*gamma + 2*C*L*P*TB*alpha ...
        + 2*C*L*P*TB*beta];
end

