function Cbb = CbbPoly(C,G,L,P,TA,alpha,beta,gamma)

% This function returns the vector of monomial coefficients for the Cbb
% polynomial which corresponds to the reaction function of firm B.

% This polynomial is derived according to the assumption LA = LB = L and 
% PA = PB = P.

% Define the polynomial coefficient vectors Cbb.
Cbb = [ -G, ...
        - 3*G*L - 3*G*TA, ...
        2*L*alpha^2 - 3*G*TA^2 - 3*G*L^2 + 2*TA*alpha^2 - 6*G*L*TA ...
        - 2*C*L*alpha - 2*C*TA*alpha + 2*C*TA*beta - 2*L*alpha*gamma ...
        - 2*TA*alpha*beta - 2*TA*alpha*gamma + 2*TA*beta*gamma ...
        - 2*L*P*alpha^2 + 2*C*L*P*alpha + 2*C*L*P*beta ...
        - 2*L*P*alpha*beta + 2*L*P*alpha*gamma + 2*L*P*beta*gamma, ...
        2*L^2*P*alpha^2 - G*TA^3 - 2*TA^2*beta^2 - G*L^3 ...
        - 2*L^2*P^2*alpha^2 - 2*L^2*P^2*beta^2 - 3*G*L*TA^2 - 3*G*L^2*TA ...
        - 2*C*L^2*alpha - 2*C*TA^2*alpha + 2*C*TA^2*beta ...
        - 2*L^2*alpha*gamma + 2*TA^2*alpha*beta - 2*TA^2*alpha*gamma ...
        + 2*TA^2*beta*gamma + 2*C*L^2*P*beta + 2*L*P*TA*alpha^2 ...
        - 4*L*P*TA*beta^2 + 2*L^2*P*alpha*beta + 2*L^2*P*alpha*gamma ...
        + 2*L^2*P*beta*gamma - 4*L^2*P^2*alpha*beta - 4*C*L*TA*alpha ...
        + 2*C*L*TA*beta + 2*L*TA*alpha*beta - 4*L*TA*alpha*gamma ...
        + 2*L*TA*beta*gamma + 2*C*L^2*P*alpha - 2*L*P*TA*alpha*beta ...
        + 2*L*P*TA*alpha*gamma + 2*L*P*TA*beta*gamma + 2*C*L*P*TA*alpha ...
        + 2*C*L*P*TA*beta];

end

