function [TBopt,DigitsAccuracy,FilterFlag] = FirmBBestResponse(SolutionsNumber,TA,C,G,LA,LB,PA,PB,alpha,beta,gamma,gamma_prime)

% This function estimates the best-response influence levels TBopt for the
% second firm (Firm B) given the influence level TA which was selected by
% the first firm (Firm A). TBopt is in a general a row-wise vector of
% optimal solutions which are actually the representive optimal solutions
% obtained by merging each final solution for every initial point.
% SolutionsNumber is the number of initial points to be generated by the
% optimizer.

% Set the dimensionality of the search space.
Dimensionality = 1;
% Set the tolerance value for the minimizer. (Preferable value = 1e-10)
Tolerance = 1e-15;
% Set the maximum number of iterations to be conducted by the optimizer.
MaxIterations = 2000;
% Set the maximum number of function evaluations to be conducted by the
% optimizer.
MaxFunctionEvaluations = 20000;
% Set the minimum digits accuracy required for the obtained set of solutions 
% to be accepted.
MinimumDigitsAccuracy = 7;

% Run the solver.
[Solutions,~,ExitFlags,~] = FirmBProfitMaximizer(Tolerance,MaxIterations,MaxFunctionEvaluations,Dimensionality,SolutionsNumber,TA,C,G,LA,LB,PA,PB,alpha,beta,gamma);

% Filter the obtained solutions.
[Solutions,FilterFlag,~,~,~,~,~,~] = FilterFirmBSolutions(Solutions,TA,ExitFlags,C,G,LA,LB,PA,PB,alpha,beta,gamma,gamma_prime);

% Extract the representative solution in case the FilterFlag is zero.
if(FilterFlag == 0)
    [TBopt,DigitsAccuracy] = ExtractRepresentativeSolution(Solutions,MinimumDigitsAccuracy);
else
    warning('Optimization procedure for Firm B failed with FilterFlag: %d',FilterFlag);
    TBopt = -1;
    DigitsAccuracy = 0;
end

end